### ISSUE TITLE
Investigate `ClusterStorageContainer` from kserve

### ISSUE THREAD

**Issue by lampajr** [opendatahub-io/model-registry-bf4-kf#254]
Investigate/explore the `ClusterStorageContainer` capability that kserve introduced in the latest release.

Idea behind this exploration:
* Provide a custom `storage-initializer` that will match URI format like `model-registry://` [1]
* This custom image "understands" the URI-specific format and it will fetch model registry data in order to retrieve the correct indexed modelArtifact - the URI should contains required information to retrieve it.
* Download the model using already existing kserve functionalities (the custom image will a wrapper of the existing one that understands the model registry URI format that we can define)
* In this way the `InferenceService` that will use model registry could be something like (already supported by kserve):
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "onnx-model"
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      storageUri: "model-registry://........"
```

[1] https://kserve.github.io/website/latest/modelserving/storage/storagecontainers/
